import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/user/Footer"
import UserLoginProvider from "@/components/Providers/UserLoginProvider";
import NextUiProviderComp from "@/components/Providers/NextUiProvider"
import Navbar from "@/components/user/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  const hiddenPath = [
    "/admin",
    "/agent",
    "/agency",
    "/owner",
    "/access-denied",
    "/login",
    "/signup",
    "/not-found"
  ]
  return (
    <html lang="en">

      <body className={inter.className}>
        
      <UserLoginProvider >
        <NextUiProviderComp>
          <Navbar hideNavPath={hiddenPath} />
      
          {children}
       <Footer hideFooterPath = {hiddenPath}/>
        </NextUiProviderComp>

      </UserLoginProvider>

      </body>
    </html>
  );
}
