import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/user/Footer"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hideFooterPath = [
    "/admin",
    "/agent",
    "/agency",
    "/owner",
    "/access-denied",
    "/login",
    "/signup",
    "/not-found"
  ]
  return (
    <html lang="en">

      <body className={inter.className}>

          {children}
       <Footer hideFooterPath = {hideFooterPath}/>
      </body>
    </html>
  );
}
